# Generated by Django 5.0.6 on 2024-06-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('servico', '0002_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('pe', 'Pendente'), ('ca', 'Cancelado'), ('an', 'Andamento'), ('ap', 'Aprovado')], max_length=2, verbose_name='Situação')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_servico', to='crm.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviço',
                'ordering': ('situacao',),
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('proxima_visita', models.DateTimeField(blank=True, null=True, verbose_name='Próxima visita')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico_itens', to='servico.ordemservico', verbose_name='ordem_de_servico')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico_item_servicos', to='servico.servico', verbose_name='servico')),
            ],
            options={
                'verbose_name': 'ordem de serviço item',
                'verbose_name_plural': 'ordens de serviço itens',
                'ordering': ('ordem_servico',),
            },
        ),
    ]
