# Generated by Django 5.0.6 on 2024-06-24 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('servico', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservicoitem',
            options={'ordering': ('-pk',), 'verbose_name': 'item da ordem de serviço', 'verbose_name_plural': 'itens da ordem de serviço'},
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_servicos', to='crm.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='ordem_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico_itens', to='servico.ordemservico', verbose_name='ordem_de_servico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico_item_servicos', to='servico.servico', verbose_name='servico'),
            preserve_default=False,
        ),
    ]
